baseURL = "https://busui.github.com"
languageCode = "zh-cn"
defaultContentLanguage = "zh-cn"
title = "CodePool"                           # site title  # 网站标题
theme = "yellow"
hasCJKLanguage = true                # has chinese/japanese/korean ? # 自动检测是否包含 中文\日文\韩文
summaryLength = 100
paginate = 5                         # 首页显示文章数量
enableEmoji = true
googleAnalytics = ""                   # your google analytics id
disqusShortname = ""                 # your discuss shortname

[author]                             # essential                     # 必需
  name = "Busui"

[blackfriday]
  smartypants = true

[[menu.main]]                        # config your menu  # 配置菜单
  name = "首页"
  weight = 10
  identifier = "home"
  url = "/"
  post = "#icon-ziyuan2"
[[menu.main]]
  name = "分类"
  weight = 20
  identifier = "categories"
  url = "/categories/"
  post = "#icon-ziyuan"
[[menu.main]]
  name = "标签"
  weight = 30
  identifier = "tags"
  url = "/tags/"
  post = "#icon-ziyuan4"
[[menu.main]]
  name = "归档"
  weight = 40
  identifier = "archive"
  url = "/archive/"
  post = "#icon-ziyuan5"
[[menu.main]]
  name = "关于"
  weight = 50
  identifier = "about"
  url = "/about/"
  post = "#icon-ziyuan1"

[taxonomies]
  category = "categories"
  tag = "tags"
  archive = "archive"

[params]
  custom_css = ["custom_css/style.css", "custom_css/github.css"]
  env = "production"
  beian = "粤ICP备19088648号-1"                           # 底部备案号
  welcome = "欢迎来访我的网站，本站所有言行仅代表个人行为，无关任何其他个体/组织。"
  siteBrand = "codepool"                                 # 网站顶部招牌名
  motto = "我至今无法否认学习是一件快乐的事儿"                 # 顶部签名

# mathjax
  enableMathJax = true                                                 # enable mathjax  # 是否使用mathjax（数学公式）

  enableSummary = true                                                 # display the article summary  # 是否显示文章摘要
  

[highlight]
  pygmentsUseClasses = true
  pygmentsCodeFences = true     # 开启```languageCode```模式
  pygmentsCodefencesGuessSyntax = true